[package]
name = "plugin-volume"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = [ "cdylib" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4"
rambot-api = { path = "../rambot-api" }
regex = "1.6"
