[workspace]

members = [
    "plugin-folder-list",
    "plugin-loop",
    "plugin-shuffle",
    "plugin-volume",
    "plugin-wave",
    "rambot",
    "rambot-api"
]

[profile.release]

lto = true
opt-level = 3
panic = 'abort'
strip = true
