[package]
name = "plugin-wave"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = [ "cdylib" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hound = "3.4"
rambot-api = { path = "../rambot-api" }
